### ISSUE TITLE
QnA: Codepen

### ISSUE THREAD

**Issue by NitkarshChourasia** [PBJI/PBJI#2]
Why do you use codepen?!

**Comment by PBJI** [comment]
@NitkarshChourasia I do not use it frequently, it is like notepad for quick demonstration.

**Comment by NitkarshChourasia** [comment]
👍🆗 okay.

**Comment by NitkarshChourasia** [comment]
What are your thoughts on JavaScript React Native and Flutter?
Personal Thoughts with experience and some facts would be better.

**Comment by PBJI** [comment]
@NitkarshChourasia, I don't have any experience or opinion in regards to both.
